"""expand audit_logs with context fields

Revision ID: 08875f3e912f
Revises: f1912cae2297
Create Date: 2026-03-13 14:56:19.147466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08875f3e912f'
down_revision: Union[str, Sequence[str], None] = 'f1912cae2297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('endpoint_path', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('http_method', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'http_method')
    op.drop_column('audit_logs', 'endpoint_path')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'metadata_json')
    # ### end Alembic commands ###
