"""add lead workflow fields

Revision ID: 27737f8ea073
Revises: 690c846b6625
Create Date: 2026-02-18 17:30:14.652190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27737f8ea073'
down_revision: Union[str, Sequence[str], None] = '690c846b6625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('status', sa.String(length=30), server_default='NEW', nullable=False))
    op.add_column('leads', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_contacted_at')
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'assigned_to')
    op.drop_column('leads', 'status')
    # ### end Alembic commands ###
