"""add soft delete to leads

Revision ID: 690c846b6625
Revises: 8889956a8990
Create Date: 2026-02-18 15:43:25.226910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690c846b6625'
down_revision: Union[str, Sequence[str], None] = '8889956a8990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leads', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'deleted_at')
    op.drop_column('leads', 'is_deleted')
    # ### end Alembic commands ###
